package com.xjtu.iron.relational.core;

import com.xjtu.iron.relational.api.RelationalTemplate;
import com.xjtu.iron.relational.api.exception.RelationalAccessException;
import com.xjtu.iron.relational.api.exception.RelationalFailureType;
import com.xjtu.iron.relational.api.statement.BatchSqlStatement;
import com.xjtu.iron.relational.api.statement.SqlParameter;
import com.xjtu.iron.relational.api.statement.SqlRoute;
import com.xjtu.iron.relational.api.statement.SqlStatement;
import com.xjtu.iron.relational.core.connection.DefaultConnectionProvider;
import com.xjtu.iron.relational.core.connection.SingleDataSourceResolver;
import com.xjtu.iron.relational.core.exception.StandardSqlExceptionTranslator;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DefaultRelationalTemplateIntegrationTest {

    private JdbcDataSource dataSource;
    private RelationalTemplate template;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:relational_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE relational_test (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(64) NOT NULL,
                        score INT
                    )
                    """);
        }

        template = new DefaultRelationalTemplate(
                new DefaultConnectionProvider(new SingleDataSourceResolver(dataSource)),
                new StandardSqlExceptionTranslator()
        );
    }

    @Test
    void updateAndQueryShouldUseTheSameStableApi() {
        template.update(SqlStatement.of(
                "test.insert",
                "INSERT INTO relational_test(name, score) VALUES (?, ?)",
                "alice",
                10
        ));

        String name = template.queryOne(
                SqlStatement.of(
                        "test.find-one",
                        "SELECT name FROM relational_test WHERE score = ?",
                        10
                ),
                resultSet -> resultSet.getString("name")
        ).orElseThrow();

        List<String> names = template.queryList(
                SqlStatement.of(
                        "test.find-list",
                        "SELECT name FROM relational_test ORDER BY id"
                ),
                resultSet -> resultSet.getString("name")
        );

        Long count = template.queryScalar(
                SqlStatement.of("test.count", "SELECT COUNT(*) FROM relational_test"),
                Long.class
        ).orElseThrow();

        assertThat(name).isEqualTo("alice");
        assertThat(names).containsExactly("alice");
        assertThat(count).isEqualTo(1L);
    }

    @Test
    void batchShouldWorkForAnyDmlSql() {
        BatchSqlStatement batch = BatchSqlStatement.of(
                "test.batch-insert",
                "INSERT INTO relational_test(name, score) VALUES (?, ?)",
                List.of(
                        List.of(SqlParameter.of("a"), SqlParameter.of(1)),
                        List.of(SqlParameter.of("b"), SqlParameter.of(2))
                )
        );

        assertThat(template.batchUpdate(batch).size()).isEqualTo(2);
        assertThat(template.queryScalar(
                SqlStatement.of("test.count-after-batch", "SELECT COUNT(*) FROM relational_test"),
                Long.class
        )).contains(2L);
    }

    @Test
    void batchAliasShouldDelegateToBatchUpdate() {
        BatchSqlStatement batch = BatchSqlStatement.of(
                "test.batch-alias-insert",
                "INSERT INTO relational_test(name, score) VALUES (?, ?)",
                List.of(List.of(SqlParameter.of("alias"), SqlParameter.of(3)))
        );

        assertThat(template.batch(batch).size()).isEqualTo(1);
    }

    @Test
    void queryOneShouldRejectMultipleRows() {
        template.update(SqlStatement.of(
                "test.insert-a",
                "INSERT INTO relational_test(name, score) VALUES (?, ?)",
                "a",
                10
        ));
        template.update(SqlStatement.of(
                "test.insert-b",
                "INSERT INTO relational_test(name, score) VALUES (?, ?)",
                "b",
                10
        ));

        assertThatThrownBy(() -> template.queryOne(
                SqlStatement.of(
                        "test.non-unique",
                        "SELECT name FROM relational_test WHERE score = ?",
                        10
                ),
                resultSet -> resultSet.getString("name")
        )).isInstanceOfSatisfying(RelationalAccessException.class, exception ->
                assertThat(exception.failureType()).isEqualTo(RelationalFailureType.NON_UNIQUE_RESULT));
    }

    @Test
    void namedRouteShouldFailFastWhenOnlySingleDataSourceIsConfigured() {
        SqlStatement routed = SqlStatement.of(
                "test.wrong-route",
                "INSERT INTO relational_test(name, score) VALUES (?, ?)",
                "a",
                1
        ).withRoute(SqlRoute.of("db-01"));

        assertThatThrownBy(() -> template.update(routed))
                .isInstanceOfSatisfying(RelationalAccessException.class, exception ->
                        assertThat(exception.failureType())
                                .isEqualTo(RelationalFailureType.DATA_SOURCE_ROUTING_ERROR));
    }

    @Test
    void translatorFailureShouldNotHideOriginalSqlException() {
        RelationalTemplate brokenTranslatorTemplate = new DefaultRelationalTemplate(
                new DefaultConnectionProvider(new SingleDataSourceResolver(dataSource)),
                (context, exception) -> {
                    throw new IllegalStateException("translator-broken");
                }
        );

        assertThatThrownBy(() -> brokenTranslatorTemplate.update(SqlStatement.of(
                "test.invalid-sql",
                "INSERT INTO missing_table(name) VALUES (?)",
                "x"
        ))).isInstanceOfSatisfying(RelationalAccessException.class, exception -> {
            assertThat(exception.failureType()).isEqualTo(RelationalFailureType.UNKNOWN);
            assertThat(exception.getCause()).isInstanceOf(SQLException.class);
            assertThat(exception.getSuppressed())
                    .anyMatch(suppressed -> suppressed instanceof IllegalStateException
                            && "translator-broken".equals(suppressed.getMessage()));
        });
    }
}
