CREATE TABLE IF NOT EXISTS iron_idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(64) NOT NULL DEFAULT 'default',
    scan_bucket INT NOT NULL DEFAULT 0,
    namespace VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(256) NOT NULL,
    route_key VARCHAR(256),
    request_hash VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    owner_token VARCHAR(128),
    version BIGINT NOT NULL DEFAULT 0,
    result_payload CLOB,
    failure_code VARCHAR(128),
    failure_message VARCHAR(1024),
    failure_retryable BOOLEAN NOT NULL DEFAULT FALSE,
    recovery_mode VARCHAR(32) NOT NULL DEFAULT 'NONE',
    window_policy VARCHAR(64) NOT NULL DEFAULT 'FIXED_FROM_FIRST_ACQUIRE',
    processing_expire_at TIMESTAMP,
    window_expire_at TIMESTAMP,
    retention_expire_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT uk_iron_idempotency_identity UNIQUE(store_name, namespace, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_iron_idempotency_recovery_scan
    ON iron_idempotency_record(store_name, scan_bucket, recovery_mode, status, processing_expire_at, id);
