CREATE TABLE IF NOT EXISTS iron_reliable_task (
    store_name         VARCHAR(64)  NOT NULL,
    namespace          VARCHAR(64)  NOT NULL,
    task_id            VARCHAR(128) NOT NULL,
    task_type          VARCHAR(64)  NOT NULL,
    business_key       VARCHAR(128) NULL,
    payload            TEXT         NOT NULL,
    route_key          VARCHAR(256) NULL,
    scan_bucket        INT          NOT NULL,
    status             VARCHAR(32)  NOT NULL,
    attempt_count      INT          NOT NULL DEFAULT 0,
    max_attempts       INT          NOT NULL,
    next_execute_at    TIMESTAMP(6) NULL,
    owner_id           VARCHAR(128) NULL,
    lease_until        TIMESTAMP(6) NULL,
    version            BIGINT       NOT NULL DEFAULT 0,
    last_error_code    VARCHAR(64)  NULL,
    last_error_message VARCHAR(1024) NULL,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    completed_at       TIMESTAMP(6) NULL,
    PRIMARY KEY (store_name, namespace, task_id),
    KEY idx_irt_due (store_name, scan_bucket, status, next_execute_at),
    KEY idx_irt_lease (store_name, scan_bucket, status, lease_until),
    KEY idx_irt_business (store_name, namespace, task_type, business_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Iron Reliable Task';
